"""
Clinical Report & Export Generator Module
Generates downloadable PDF Clinical Diagnostic Reports and CSV exports for patient records.
"""

import io
import pandas as pd
from datetime import datetime


def generate_csv_export(patient_dict: dict, pred_results: dict) -> str:
    """
    Generates a CSV string containing patient input parameters and model predictions.
    """
    record = {
        "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Diagnosis": "HEART DISEASE DETECTED" if pred_results["is_disease"] else "NO DISEASE DETECTED",
        "Probability (%)": f"{pred_results['mean_prob']*100:.2f}%",
        "Confidence Score (%)": f"{pred_results['confidence_pct']:.1f}%",
        "Uncertainty (±std)": f"±{pred_results['uncertainty_std']*100:.2f}%",
        "Risk Level": pred_results["risk_level"]
    }
    # Append input patient features
    record.update(patient_dict)

    df_export = pd.DataFrame([record])
    return df_export.to_csv(index=False)


def generate_pdf_report(patient_dict: dict, pred_results: dict) -> bytes:
    """
    Generates a downloadable PDF Clinical Diagnostic Report using fpdf2 if available,
    or fallback clean formatted text report buffer.
    """
    try:
        from fpdf import FPDF

        class ClinicalReportPDF(FPDF):
            def header(self):
                self.set_font("Helvetica", "B", 16)
                self.set_text_color(10, 37, 64)
                self.cell(0, 10, "HQ-KAN CLINICAL DIAGNOSTIC REPORT", border=False, ln=True, align="C")
                self.set_font("Helvetica", "I", 9)
                self.set_text_color(100, 116, 139)
                self.cell(0, 5, "Hybrid Quantum Kolmogorov-Arnold Network with Bayesian Uncertainty", border=False, ln=True, align="C")
                self.ln(5)
                self.set_draw_color(0, 168, 150)
                self.set_linewidth(0.8)
                self.line(10, 28, 200, 28)
                self.ln(5)

            def footer(self):
                self.set_y(-15)
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(148, 163, 184)
                self.cell(0, 10, f"Page {self.page_no()} | Confidential Medical AI Report | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C")

        pdf = ClinicalReportPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # 1. Summary Box
        is_disease = pred_results["is_disease"]
        pdf.set_font("Helvetica", "B", 12)
        if is_disease:
            pdf.set_fill_color(254, 242, 242)
            pdf.set_text_color(155, 28, 28)
            pdf.cell(0, 12, f"  DIAGNOSIS: HIGH RISK OF HEART DISEASE ({pred_results['mean_prob']*100:.1f}%)", ln=True, fill=True)
        else:
            pdf.set_fill_color(240, 253, 244)
            pdf.set_text_color(3, 84, 63)
            pdf.cell(0, 12, f"  DIAGNOSIS: NO HEART DISEASE DETECTED ({(1-pred_results['mean_prob'])*100:.1f}% Healthy)", ln=True, fill=True)

        pdf.ln(4)

        # 2. Key Metrics Table
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, "Model Confidence & Uncertainty Quantification:", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(65, 7, f"• Disease Probability: {pred_results['mean_prob']*100:.2f}%", ln=False)
        pdf.cell(65, 7, f"• Bayesian Confidence: {pred_results['confidence_pct']:.1f}%", ln=False)
        pdf.cell(60, 7, f"• Uncertainty (±std): ±{pred_results['uncertainty_std']*100:.2f}%", ln=True)
        pdf.cell(65, 7, f"• Assigned Risk Level: {pred_results['risk_level']}", ln=True)

        pdf.ln(6)

        # 3. Patient Vitals Table
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(10, 37, 64)
        pdf.cell(0, 8, "Patient Clinical Features & Measurements:", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_fill_color(248, 250, 252)

        col_w = 92
        items = list(patient_dict.items())
        for i in range(0, len(items), 2):
            k1, v1 = items[i]
            str1 = f"{k1}: {v1}"
            pdf.cell(col_w, 6, f"  {str1}", border=1, ln=False, fill=True)
            if i + 1 < len(items):
                k2, v2 = items[i+1]
                str2 = f"{k2}: {v2}"
                pdf.cell(col_w, 6, f"  {str2}", border=1, ln=True, fill=True)
            else:
                pdf.cell(col_w, 6, "", border=1, ln=True, fill=True)

        pdf.ln(8)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(100, 116, 139)
        pdf.multi_cell(0, 4, "Medical Disclaimer: This report is generated by an artificial intelligence system (HQ-KAN) for clinical decision support. Final diagnosis must be confirmed by a licensed medical practitioner.")

        return bytes(pdf.output())

    except Exception:
        # Fallback text buffer if fpdf2 is not available
        output = io.StringIO()
        output.write("=====================================================\n")
        output.write("        HQ-KAN CLINICAL DIAGNOSTIC REPORT\n")
        output.write("=====================================================\n")
        output.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        output.write(f"DIAGNOSIS: {'HEART DISEASE DETECTED' if pred_results['is_disease'] else 'NO DISEASE DETECTED'}\n")
        output.write(f"Probability: {pred_results['mean_prob']*100:.2f}%\n")
        output.write(f"Confidence Score: {pred_results['confidence_pct']:.1f}%\n")
        output.write(f"Uncertainty (±std): ±{pred_results['uncertainty_std']*100:.2f}%\n")
        output.write(f"Risk Level: {pred_results['risk_level']}\n\n")
        output.write("PATIENT CLINICAL VITAL MEASUREMENTS:\n")
        for k, v in patient_dict.items():
            output.write(f"  - {k}: {v}\n")
        output.write("\n=====================================================\n")
        output.write("Medical Disclaimer: Clinical decision support tool. Confirm with physician.\n")
        return output.getvalue().encode("utf-8")
